-- CREATE USER poller_user WITH PASSWORD 'poller';
GRANT USAGE, CREATE ON SCHEMA public TO poller_user;
GRANT ALL PRIVILEGES ON DATABASE poller TO poller_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO poller_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO poller_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO poller_user;

-- CREATE DATABASE poller;