name: Unit Test
on: [push, workflow_dispatch]
jobs:
  # Frontend unit test
  frontend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm ci
        run: npm ci
        working-directory: ./frontend
      - name: npm run test
        run: npm run test
        working-directory: ./frontend